name: VRT Approve
on:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: |
            mobile
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: mobile/package.json
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: mobile/.node-version
          cache: 'pnpm'
          cache-dependency-path: 'mobile/**/pnpm-lock.yaml'
      - name: Install fonts
        # 日本語が文字化けするためフォントをインストールする
        run: sudo apt install language-pack-ja fontconfig fonts-ipafont
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Storybook VRT
        run: pnpm vrt:approve
      - name: Configure Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Update VRT Approve
        run: |
          git status
          git diff
          git add vrt/public/report/expected
          git commit -m "VRT Approve" --no-verify
          git push origin ${{ github.head_ref }} --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
